# Generated by Django 4.1.5 on 2023-02-01 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField(blank=True, db_column='Date', null=True)),
                ('day', models.TextField(blank=True, db_column='Day', null=True)),
                ('week', models.IntegerField(blank=True, db_column='Week', null=True)),
                ('month', models.IntegerField(blank=True, db_column='Month', null=True)),
                ('year', models.IntegerField(blank=True, db_column='Year', null=True)),
                ('quarter', models.IntegerField(blank=True, db_column='Quarter', null=True)),
            ],
            options={
                'db_table': 'date_table',
                'managed': False,
            },
        ),
    ]
