# Generated by Django 4.1.5 on 2023-02-01 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_finance', '0002_datetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposits',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_finance.datetable'),
        ),
        migrations.AlterField(
            model_name='epos',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_finance.datetable'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_finance.datetable'),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_finance.datetable'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_finance.datetable'),
        ),
        migrations.AlterField(
            model_name='safecount',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_finance.datetable'),
        ),
    ]
