# Generated by Django 4.1.5 on 2023-02-03 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_finance', '0004_staff_hoursworked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='hours',
        ),
    ]
