# Generated by Django 4.1.5 on 2023-02-03 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_finance', '0005_remove_staff_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositsReturned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_finance.datetable')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_finance.sites')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'deposits',
            },
        ),
        migrations.CreateModel(
            name='DepositsTaken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_finance.datetable')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_finance.sites')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'deposits',
            },
        ),
        migrations.RemoveField(
            model_name='deposits',
            name='category',
        ),
        migrations.RemoveField(
            model_name='deposits',
            name='date',
        ),
        migrations.RemoveField(
            model_name='deposits',
            name='site',
        ),
        migrations.RemoveField(
            model_name='deposits',
            name='user',
        ),
        migrations.DeleteModel(
            name='DepositCategory',
        ),
        migrations.DeleteModel(
            name='Deposits',
        ),
        migrations.AddField(
            model_name='depositsreturned',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_finance.depositstaken'),
        ),
    ]
