# Generated by Django 4.1.5 on 2023-02-03 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_finance', '0006_depositsreturned_depositstaken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositsreturned',
            name='notes',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='depositstaken',
            name='notes',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
