# Generated by Django 4.1.5 on 2023-02-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_finance', '0007_depositsreturned_notes_depositstaken_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='category',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='date',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='site',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='user',
        ),
        migrations.AddField(
            model_name='hoursworked',
            name='wage',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='OrderCategory',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
