# Generated by Django 4.1.5 on 2023-02-04 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_finance', '0008_remove_orders_category_remove_orders_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depositsreturned',
            options={'verbose_name_plural': 'deposits_returned'},
        ),
        migrations.AlterModelOptions(
            name='depositstaken',
            options={'verbose_name_plural': 'deposits_taken'},
        ),
        migrations.CreateModel(
            name='CashHandover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_finance.datetable')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_finance.sites')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'cash_handover',
            },
        ),
    ]
