# Generated by Django 4.1.5 on 2023-02-04 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_finance', '0010_alter_cashhandover_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashhandover',
            name='category',
            field=models.CharField(choices=[('IP', 'In Person'), ('BK', 'Bank')], default='IP', max_length=2),
        ),
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.CharField(choices=[('BS', 'Bar Staff'), ('BB', 'Bar Back'), ('CL', 'Cleaner'), ('AM', 'Assistant Manager'), ('MA', 'Manager')], default='BS', max_length=2),
        ),
    ]
