# Generated by Django 4.1.5 on 2023-02-05 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_finance', '0011_alter_cashhandover_category_alter_staff_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depositsreturned',
            old_name='amount',
            new_name='amount_out',
        ),
        migrations.RenameField(
            model_name='depositstaken',
            old_name='amount',
            new_name='amount_in',
        ),
    ]
